### ISSUE TITLE
After latest update, no longer works- TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by insajd** [haberda/update_lights#1]
Turning on light, getting error in log: **TypeError: expected string or bytes-like object**

Update lights version: Installed: 2113049
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
 Add-on version: 0.2.3
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (armv7 / odroid-xu)
 Home Assistant Core: 0.106.6
 Home Assistant Supervisor: 209

```
2020-03-17 18:05:19.120937 WARNING main_update_lights: ------------------------------------------------------------
2020-03-17 18:05:19.122602 WARNING main_update_lights: Unexpected error in worker for App main_update_lights:
2020-03-17 18:05:19.124103 WARNING main_update_lights: Worker Ags: {'id': '482aeefb35d84b0bb1fbed874f7f27f4', 'name': 'main_update_lights', 'objectid': '10a1a1a6bfd24976a7666ecac5c0de23', 'type': 'scheduler', 'function': <bound method update_lights.time_change of <update_lights.update_lights object at 0xb4b8c9a0>>, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'interval': 60, '__thread_id': 'thread-5'}}
2020-03-17 18:05:19.125591 WARNING main_update_lights: ------------------------------------------------------------
2020-03-17 18:05:19.129184 WARNING main_update_lights: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 95, in time_change
    self.adjust_light(entities, threshold, transition)
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 301, in adjust_light
    pct = self.pct()
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 144, in pct
    start_i_ts = datetime.datetime.combine(start_ts.date(), self.parse_time(self.start_index))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1810, in parse_time
    return await self.AD.sched.parse_time(time_str, name, aware)
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 576, in parse_time
    return self.make_naive((await self._parse_time(time_str, name))["datetime"]).time()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 589, in _parse_time
    parts = re.search('^(\d+)-(\d+)-(\d+)\s+(\d+):(\d+):(\d+)$', time_str)
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

2020-03-17 18:05:19.130563 WARNING main_update_lights: ------------------------------------------------------------
```

**Comment by haberda** [comment]
What does your apps.yaml app setup look like? Can you post it?
If you have a time set in that for an index time it has to be in quotes. I'll do some error checking on that for the next update.
Either way, please post your current app setup so I can make sure that is the problem.

**Comment by insajd** [comment]
Yes, those were quotes around time in settings! Before I had end_index: sunrise + 03:00:00, and after removal it stayed unquoted.

Thank you for your app, it's working great! Love this threshold thing. Haven't fully yet comprehended usage of start/end indexes.

My new working config is such:
```
main_update_lights:
  module: update_lights
  class: update_lights
  entities:
    - light.right_bulb
    - light.left_bulb
    - light.bedroom
    - light.living_room
    - light.kitchen
    - light.color
  brightness_threshold: 25
  max_brightness_level: 100
  min_brightness_level: 1
  brightness_unit: 'percent'
  sleep_entity: 
    - binary_sensor.asleep_time
  start_time: sunset - 3:00:00
  end_time: sunrise + 3:00:00
  start_index: '17:00:00'
  end_index: '8:00:00'
  transition: 5
  keep_lights_on: False
  disable_entity: 
    - switch.circadian_lighting_circadian_lighting
  sensor_log: sensor.main_lights
```

**Comment by haberda** [comment]
Excellent! I'm glad it's working again and happy that someone else finds it useful.

The idea behind the index is so that the gradient is different whether we are before the midpoint or after. So you can have for example a sharp gradient in the evening so that dimming takes place quickly, and a gradual gradient so the lights get brighter more slowly after the midpoint. I use this so my lights get dim fast at night and are still fairly dim when I get up in the morning for work.

If you don't use the index then the start and end times are used and the gradient is continuous all night.
