### ISSUE TITLE
App not working - invalid time string: 61200

### ISSUE THREAD

**Issue by insajd** [haberda/update_lights#5]
Home Assistant 0.113.0
I think after update, app no longer works. Noticed when lights didn't change in the evening.
Here is the log when toggling lights:

```
2020-07-24 23:53:24.627305 WARNING main_update_lights: ------------------------------------------------------------
2020-07-24 23:53:24.627594 WARNING main_update_lights: Unexpected error in worker for App main_update_lights:
2020-07-24 23:53:24.627796 WARNING main_update_lights: Worker Ags: {'id': '64944d60d44c423c9ab57243a416792a', 'name': 'main_update_lights', 'objectid': '4811649cde87490e9e99ac2639c289ee', 'type': 'state', 'function': <bound method update_lights.state_change of <update_lights.update_lights object at 0x7f2e31afa400>>, 'attribute': 'state', 'entity': 'light.left_bulb', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 4, 'kwargs': {'__thread_id': 'thread-4'}}
2020-07-24 23:53:24.628036 WARNING main_update_lights: ------------------------------------------------------------
2020-07-24 23:53:24.631696 WARNING main_update_lights: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 777, in worker
    funcref(entity, attr, old_state, new_state,
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 107, in state_change
    self.adjust_light(entity, threshold, transition)
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 313, in adjust_light
    pct = self.pct()
  File "/config/appdaemon/apps/update_lights/update_lights.py", line 141, in pct
    start_ts = datetime.datetime.combine(self.date(), self.parse_time(self.start_time))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1810, in parse_time
    return await self.AD.sched.parse_time(time_str, name, aware)
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 576, in parse_time
    return self.make_naive((await self._parse_time(time_str, name))["datetime"]).time()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 656, in _parse_time
    raise ValueError("invalid time string: %s", time_str)
ValueError: ('invalid time string: %s', '61200')
```

**Comment by haberda** [comment]
Can you post your apps.yaml configuration? It looks like the time string is malformed. The latest update did not change any time handling code.

**Comment by insajd** [comment]
You're probably right, forgot that I tried changing start/end times and indexes.

```
main_update_lights:
  module: update_lights
  class: update_lights
#  run_every: 180
  entities:
    - light.right_bulb
    - light.left_bulb
    - light.bedroom
    - light.living_room
    - light.kitchen
    - light.color
  brightness_threshold: 25
  brightness_unit: 'percent'
  sleep_entity: 
    - binary_sensor.asleep_time
  sleep_condition: on
  start_time: 17:00:00
  end_time: 9:00:00
  start_index: 12:00:00
  end_index: 18:00:00
  transition: 5
  keep_lights_on: False
  disable_entity: 
    - input_boolean.circadian_lighting
  sensor_log: sensor.main_lights
```

**Comment by insajd** [comment]
Oh, now i see it. Times need to  be quoted. Thanks for your input!
